name: Update release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Release Branch"
        required: true
        type: string
jobs:
  obs_release_uos20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git remote add openatom https://github.com/deepin-community/linyaps
          git fetch openatom --no-tags
          git reset --hard openatom/${{ inputs.branch }}
          rm -r .github || true
      - run: |
          # 禁止单元测试
          sed -i '/set(ENABLE_TESTING/{n; s/ON/OFF/}' CMakeLists.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: obs_release_uos20
          create_branch: true
          push_options: --force
          commit_message: Automated Change
