name: Update release
on:
  workflow_dispatch:
jobs:
  obs_release_deepin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Get latest release branch
        id: detect_branch
        run: |
          TARGET_BRANCH=$(git ls-remote --heads https://github.com/deepin-community/linyaps | grep 'release/[0-9]\.' | awk -F'/' '{print $NF}' | sort -V | tail -n 1)
          echo "target_branch=${TARGET_BRANCH}" >> $GITHUB_OUTPUT

      - run: |
          git remote add upstream https://github.com/deepin-community/linyaps
          git fetch upstream --no-tags
          git reset --hard upstream/release/${{ steps.detect_branch.outputs.target_branch }}
          rm -r .github || true

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: obs_release_deepin
          create_branch: true
          push_options: --force
          commit_message: Automated Change

  obs_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Get latest release branch
        id: detect_branch
        run: |
          TARGET_BRANCH=$(git ls-remote --heads https://github.com/deepin-community/linyaps | grep 'release/[0-9]\.' | awk -F'/' '{print $NF}' | sort -V | tail -n 1)
          echo "target_branch=${TARGET_BRANCH}" >> $GITHUB_OUTPUT

      - run: |
          git remote add upstream https://github.com/deepin-community/linyaps
          git fetch upstream --no-tags
          git reset --hard upstream/release/${{ steps.detect_branch.outputs.target_branch }}
          rm -r .github || true

      - run: |
          # 删除patch
          rm -r debian/patches || true
          # 删除preloader相关的代码
          sed -i '/preloader/d' debian/linglong-bin.postinst debian/linglong-bin.install debian/linglong-bin.postinst
          # 删除config.json
          sed -i '\#etc/linglong/config.json#d' debian/linglong-bin.install
          # 禁止单元测试
          sed -i '/set(ENABLE_TESTING/{n; s/ON/OFF/}' CMakeLists.txt

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: obs_release
          create_branch: true
          push_options: --force
          commit_message: Automated Change
